### ISSUE TITLE
Model Fails when we change batch size

### ISSUE THREAD

**Issue by tayalkshitij** [tkipf/kegra#48]
For Cora dataset if I change the batch size to say 100 the model fails to run. 

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot multiply A and B because inner dimension does not match: 2708 vs. 100.  Did you forget a transpose?  Dimensions of A: [100, 2708).  Dimensions of B: [100,1433]
	 [[{{node graph_convolution_1/SparseTensorDenseMatMul/SparseTensorDenseMatMul}}]]

**Comment by tkipf** [comment]
This implementation does not support mini-batch training or changing the
batch size.

**Comment by tayalkshitij** [comment]
Thanks for the reply. Does Pytorch or Tensorflow version supports mini-batch ?

**Comment by tkipf** [comment]
No, but you might want to have a look here: dgl.ai

**Comment by tayalkshitij** [comment]
Thanks
