### ISSUE TITLE
Convert string error. Any comments?

### ISSUE THREAD

**Issue by tigerneil** [tkipf/kegra#5]
run `python train.py` I got following error. Seems scipy problem. But I can't figure out it. 

The information:
```
Using TensorFlow backend.
Loading cora dataset...
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    X, A, y = load_data(dataset=DATASET)
  File "/Users/Tiger/anaconda/envs/rllab3/lib/python3.5/site-packages/kegra-0.0.1-py3.5.egg/kegra/utils.py", line 20, in load_data
    features = sp.csr_matrix(idx_features_labels[:, 1:-2], dtype=np.float32)
  File "/Users/Tiger/anaconda/envs/rllab3/lib/python3.5/site-packages/scipy/sparse/compressed.py", line 79, in __init__
    self._set_self(self.__class__(coo_matrix(arg1, dtype=dtype)))
  File "/Users/Tiger/anaconda/envs/rllab3/lib/python3.5/site-packages/scipy/sparse/coo.py", line 182, in __init__
    self.data = self.data.astype(dtype, copy=False)
ValueError: could not convert string to float: "b'0'"
```

**Comment by tkipf** [comment]
Interesting - haven't seen this before. Could be an issue related to python 3.5. Would you mind trying this in python 2.7? I'll look into it in the meantime.

**Comment by tigerneil** [comment]
I check it now.
