### ISSUE TITLE
Face TypeError during load data

### ISSUE THREAD

**Issue by Wilson-ZHANG** [tkipf/kegra#50]
As the format of Cora Dataset(cora.cites & cora.content), I generate similar data as Cora. However, It gets error below after a few times modification on my data.
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    X, A, y = load_data(cites_path, content_path)
  File "/data/zhangqifan/projects/keras-gcn-master/kegra/utils.py", line 26, in load_data
    edges = np.array(list(map(idx_map.get, edges_unordered.flatten())), dtype=np.int64).reshape(edges_unordered.shape)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Could you give me some ideas about addressing this problem?
Thanks!

**Comment by WangFeng666** [comment]
I have also encountered this problem. For me, it is because some nodes in the edgelists(.cites) did not have features and labels, and when i make all nodes have features and labels, there is no problem. I wonder that could't semi-supervise learning if there is no feature and label on some nodes?

**Comment by DonghanHe** [comment]
> I have also encountered this problem. For me, it is because some nodes in the edgelists(.cites) did not have features and labels, and when i make all nodes have features and labels, there is no problem. I wonder that could't semi-supervise learning if there is no feature and label on some nodes?

yes. I believe if you initialize a trainable feature for each of those nodes that doesn't have a feature, backpropagation can train it easily.
